mode: yaml
resources:
  - url: /local/defaults.js
    type: module
  - url: /local/cards/clock-weather-card.js
    type: module
  - url: /local/cards/sidebar-card.js
    type: module
  - url: /local/cards/floorplan.js
    type: module
  - url: /local/backgrounds/animated-background.js
    type: module