mode: yaml
resources:
  - url: /local/cards/clock-weather-card.js
    type: module
  - url: /local/cards/sticky_note_card.js
    type: module
  - url: /local/cards/sidebar-card.js
    type: module
  - url: /local/cards/floorplan.js
    type: module
  - url: /local/cards/animated-background.js
    type: module